query_ca_raw <- dbSendQuery(con, 
                            "SELECT find_id, part_id, site_dt, site_id, ca_id, lab_dt, culture_id, culture_en, region_id, region_dt, find_character_id, find_character_en, type_dt, main, ars+ni+sb+ag, cu, sn, pb, zn, bi, ag, sb, ars, fe, ni, co, au 
                            FROM cau.ca LEFT JOIN cau.find USING (find_id, site_id) LEFT JOIN cau.site USING (site_id) LEFT JOIN stf.lab USING (lab_id) LEFT JOIN cau.feature USING (feature_id, site_id) LEFT JOIN cau.culture USING (culture_id) LEFT JOIN cau.find_character USING (find_character_id) LEFT JOIN cau.type USING (type_id) LEFT JOIN cau.main USING (main_id) LEFT JOIN cau.region USING (region_id) 
                            GROUP BY find_id, part_id, site_id, site_dt, ca_id, lab_dt, culture_id, culture_en, region_id, region_dt, find_character_id, find_character_en, type_dt, main, cu, sn, pb, zn, bi, ag, sb, ars, fe, ni, co, au;")

ca <- dbFetch(query_ca_raw)
ca$culture_id <- as.character(ca$culture_id)
ca <- rename(ca, site = site_dt)
ca <- rename(ca, culture = culture_en)
ca <- rename(ca, region = region_dt)
ca <- rename(ca, type = type_dt)
ca <- rename(ca, lab = lab_dt)
ca <- rename(ca, SUMME = "?column?")
ca <- rename(ca, find_character = find_character_en)
ca <- rename(ca, Cu = cu)
ca <- rename(ca, Sn = sn)
ca <- rename(ca, Pb = pb)
ca <- rename(ca, Zn = zn)
ca <- rename(ca, Bi = bi)
ca <- rename(ca, Ag = ag)
ca <- rename(ca, Sb = sb)
ca <- rename(ca, As = ars)
ca <- rename(ca, Fe = fe)
ca <- rename(ca, Ni = ni)
ca <- rename(ca, Co = co)
ca <- rename(ca, Au = au)